name: Setup Project
description: Setup Node.js and install dependencies
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version-file: 'package.json'
        cache: 'pnpm'
    - run: pnpm insall
      shell: bash
